/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.students.sportsutilityshop;

/**
 *
 * @author Leonard Benny
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setSize(1024,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        LoginFields = new javax.swing.JPanel();
        LoginPassword = new javax.swing.JPasswordField();
        LoginUserName = new javax.swing.JTextField();
        LoginPasswordText = new javax.swing.JLabel();
        LoginUserNameText = new javax.swing.JLabel();
        LoginRadioSk = new javax.swing.JRadioButton();
        LoginRadioCs = new javax.swing.JRadioButton();
        CreateNewAccount = new javax.swing.JLabel();
        LoginTitle = new javax.swing.JLabel();
        OnlineSportsTitle = new javax.swing.JLabel();
        SkDashboard = new javax.swing.JPanel();
        SkLogout = new javax.swing.JButton();
        SkDashboardTitle = new javax.swing.JLabel();
        SkDashboardMenu = new javax.swing.JPanel();
        SkDashboardMenuHelp = new javax.swing.JButton();
        SkDashboardMenuItems = new javax.swing.JButton();
        SkDashboardMenuUsers = new javax.swing.JButton();
        SkDashboardMenuAddItem = new javax.swing.JButton();
        SkDashboardMenuAddUser = new javax.swing.JButton();
        SkDashboardMenuOverdues = new javax.swing.JButton();
        SkDashboardMenuReport = new javax.swing.JButton();
        SkItems = new javax.swing.JPanel();
        SkItemScroll = new javax.swing.JScrollPane();
        SkItemsTable = new javax.swing.JTable();
        SkItemDescriptionTitle = new javax.swing.JLabel();
        SkItemDescription = new javax.swing.JLabel();
        SkCustomers = new javax.swing.JPanel();
        SkCustomerScroll = new javax.swing.JScrollPane();
        SkCustomerTable = new javax.swing.JTable();
        SkCustomerDescriptionTitle = new javax.swing.JLabel();
        SkCustomerDescription = new javax.swing.JLabel();
        SkOverdues = new javax.swing.JPanel();
        SkOverdueScroll = new javax.swing.JScrollPane();
        SkOverdueTable = new javax.swing.JTable();
        SkOverdueDescriptionTitle = new javax.swing.JLabel();
        SkOverdueDescription = new javax.swing.JLabel();
        SkReports = new javax.swing.JPanel();
        SkItemsReport = new javax.swing.JButton();
        SkCustomersReport = new javax.swing.JButton();
        SkReportTitle = new javax.swing.JLabel();
        CsDashboard = new javax.swing.JPanel();
        CsLogout = new javax.swing.JButton();
        CsDashboardTitle = new javax.swing.JLabel();
        CsDashboardMenu = new javax.swing.JPanel();
        CsDashboardMenuHelp = new javax.swing.JButton();
        CsDashboardMenuItems = new javax.swing.JButton();
        CsDashboardMenuUsers = new javax.swing.JButton();
        CsDashboardMenuAddItem = new javax.swing.JButton();
        CsDashboardMenuAddUser = new javax.swing.JButton();
        CsItems = new javax.swing.JPanel();
        CsItemScroll = new javax.swing.JScrollPane();
        CsItemsTable = new javax.swing.JTable();
        CsItemDescriptionTitle = new javax.swing.JLabel();
        CsItemDescription = new javax.swing.JLabel();
        CsRentItems = new javax.swing.JPanel();
        CsRentItemScroll = new javax.swing.JScrollPane();
        CsRentItemTable = new javax.swing.JTable();
        CsRentItemDescriptionTitle = new javax.swing.JLabel();
        CsRentItemDescription = new javax.swing.JLabel();
        CsOverdueItems = new javax.swing.JPanel();
        CsOverdueScroll = new javax.swing.JScrollPane();
        CsOverdueTable = new javax.swing.JTable();
        CsOverdueDescriptionTitle = new javax.swing.JLabel();
        CsOverdueDescription = new javax.swing.JLabel();
        CsPurchasedItems = new javax.swing.JPanel();
        CsPurchasedItemScroll = new javax.swing.JScrollPane();
        CsPurchasedItemsTable = new javax.swing.JTable();
        CsPurchasedItemDescriptionTitle = new javax.swing.JLabel();
        CsPurchasedItemDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        LoginPanel.setBackground(new java.awt.Color(0, 102, 153));
        LoginPanel.setLayout(null);

        LoginFields.setBackground(new java.awt.Color(255, 255, 255));
        LoginFields.setLayout(null);
        LoginFields.add(LoginPassword);
        LoginPassword.setBounds(210, 120, 230, 40);
        LoginFields.add(LoginUserName);
        LoginUserName.setBounds(210, 70, 230, 40);

        LoginPasswordText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginPasswordText.setText("Password :");
        LoginFields.add(LoginPasswordText);
        LoginPasswordText.setBounds(120, 120, 160, 40);

        LoginUserNameText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginUserNameText.setText("Username :");
        LoginFields.add(LoginUserNameText);
        LoginUserNameText.setBounds(120, 70, 160, 40);

        LoginRadioSk.setText("ShopKeeper");
        LoginFields.add(LoginRadioSk);
        LoginRadioSk.setBounds(310, 170, 110, 25);

        LoginRadioCs.setText("Customer");
        LoginFields.add(LoginRadioCs);
        LoginRadioCs.setBounds(210, 170, 100, 25);

        CreateNewAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateNewAccount.setForeground(new java.awt.Color(0, 0, 153));
        CreateNewAccount.setText("Create a customer account ?");
        LoginFields.add(CreateNewAccount);
        CreateNewAccount.setBounds(220, 210, 220, 17);

        LoginTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        LoginTitle.setForeground(new java.awt.Color(153, 153, 153));
        LoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTitle.setText("Login");
        LoginFields.add(LoginTitle);
        LoginTitle.setBounds(80, 10, 430, 60);

        LoginPanel.add(LoginFields);
        LoginFields.setBounds(240, 220, 550, 280);

        OnlineSportsTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        OnlineSportsTitle.setForeground(new java.awt.Color(204, 204, 204));
        OnlineSportsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OnlineSportsTitle.setText("Online Sports Utility Shop");
        LoginPanel.add(OnlineSportsTitle);
        OnlineSportsTitle.setBounds(0, 40, 1020, 100);

        getContentPane().add(LoginPanel);

        SkDashboard.setBackground(new java.awt.Color(0, 102, 153));
        SkDashboard.setLayout(null);

        SkLogout.setText("Logout");
        SkDashboard.add(SkLogout);
        SkLogout.setBounds(930, 10, 79, 25);

        SkDashboardTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SkDashboardTitle.setForeground(new java.awt.Color(204, 204, 204));
        SkDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SkDashboardTitle.setText("Online Sports Utility Shop");
        SkDashboard.add(SkDashboardTitle);
        SkDashboardTitle.setBounds(0, 20, 1020, 100);

        SkDashboardMenu.setBackground(new java.awt.Color(255, 255, 255));
        SkDashboardMenu.setLayout(null);

        SkDashboardMenuHelp.setText("Help");
        SkDashboardMenu.add(SkDashboardMenuHelp);
        SkDashboardMenuHelp.setBounds(840, 0, 120, 40);

        SkDashboardMenuItems.setText("Items");
        SkDashboardMenu.add(SkDashboardMenuItems);
        SkDashboardMenuItems.setBounds(0, 0, 140, 40);

        SkDashboardMenuUsers.setText("Users");
        SkDashboardMenu.add(SkDashboardMenuUsers);
        SkDashboardMenuUsers.setBounds(140, 0, 140, 40);

        SkDashboardMenuAddItem.setText("Add Item");
        SkDashboardMenu.add(SkDashboardMenuAddItem);
        SkDashboardMenuAddItem.setBounds(280, 0, 140, 40);

        SkDashboardMenuAddUser.setText("Add User");
        SkDashboardMenu.add(SkDashboardMenuAddUser);
        SkDashboardMenuAddUser.setBounds(420, 0, 140, 40);

        SkDashboardMenuOverdues.setText("Check Overdues");
        SkDashboardMenu.add(SkDashboardMenuOverdues);
        SkDashboardMenuOverdues.setBounds(560, 0, 140, 40);

        SkDashboardMenuReport.setText("Print Report");
        SkDashboardMenu.add(SkDashboardMenuReport);
        SkDashboardMenuReport.setBounds(700, 0, 140, 40);

        SkDashboard.add(SkDashboardMenu);
        SkDashboardMenu.setBounds(30, 130, 960, 40);

        SkItems.setBackground(new java.awt.Color(255, 255, 255));
        SkItems.setLayout(null);

        SkItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemId", "ItemName", "ItemBrand", "ItemColour", "ItemStock", "PurchasePrice", "RentalPrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SkItemScroll.setViewportView(SkItemsTable);

        SkItems.add(SkItemScroll);
        SkItemScroll.setBounds(0, 0, 960, 380);

        SkItemDescriptionTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SkItemDescriptionTitle.setText("Description:");
        SkItems.add(SkItemDescriptionTitle);
        SkItemDescriptionTitle.setBounds(10, 410, 90, 30);

        SkItemDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SkItems.add(SkItemDescription);
        SkItemDescription.setBounds(100, 410, 850, 30);

        SkDashboard.add(SkItems);
        SkItems.setBounds(30, 180, 960, 490);

        SkCustomers.setBackground(new java.awt.Color(255, 255, 255));
        SkCustomers.setLayout(null);

        SkCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerId", "CustomerName", "CustomerContact", "UserName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SkCustomerScroll.setViewportView(SkCustomerTable);

        SkCustomers.add(SkCustomerScroll);
        SkCustomerScroll.setBounds(0, 0, 960, 380);

        SkCustomerDescriptionTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SkCustomerDescriptionTitle.setText("Address :");
        SkCustomers.add(SkCustomerDescriptionTitle);
        SkCustomerDescriptionTitle.setBounds(10, 410, 90, 30);

        SkCustomerDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SkCustomers.add(SkCustomerDescription);
        SkCustomerDescription.setBounds(100, 410, 850, 30);

        SkDashboard.add(SkCustomers);
        SkCustomers.setBounds(30, 180, 960, 490);

        SkOverdues.setBackground(new java.awt.Color(255, 255, 255));
        SkOverdues.setLayout(null);

        SkOverdueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerId", "CustomerName", "CustomerContact", "OverdueItems"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SkOverdueScroll.setViewportView(SkOverdueTable);

        SkOverdues.add(SkOverdueScroll);
        SkOverdueScroll.setBounds(0, 0, 960, 380);

        SkOverdueDescriptionTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SkOverdueDescriptionTitle.setText("Description :");
        SkOverdues.add(SkOverdueDescriptionTitle);
        SkOverdueDescriptionTitle.setBounds(10, 410, 90, 30);

        SkOverdueDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SkOverdues.add(SkOverdueDescription);
        SkOverdueDescription.setBounds(100, 410, 850, 30);

        SkDashboard.add(SkOverdues);
        SkOverdues.setBounds(30, 180, 960, 490);

        SkReports.setBackground(new java.awt.Color(255, 255, 255));
        SkReports.setLayout(null);

        SkItemsReport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SkItemsReport.setText("List of Items");
        SkReports.add(SkItemsReport);
        SkItemsReport.setBounds(530, 110, 290, 230);

        SkCustomersReport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SkCustomersReport.setText("List of Customers");
        SkReports.add(SkCustomersReport);
        SkCustomersReport.setBounds(120, 110, 290, 230);

        SkReportTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SkReportTitle.setForeground(new java.awt.Color(153, 153, 153));
        SkReportTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SkReportTitle.setText("Report Section");
        SkReports.add(SkReportTitle);
        SkReportTitle.setBounds(0, 10, 960, 60);

        SkDashboard.add(SkReports);
        SkReports.setBounds(30, 180, 960, 490);

        getContentPane().add(SkDashboard);

        CsDashboard.setBackground(new java.awt.Color(0, 102, 153));
        CsDashboard.setLayout(null);

        CsLogout.setText("Logout");
        CsDashboard.add(CsLogout);
        CsLogout.setBounds(930, 10, 79, 25);

        CsDashboardTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        CsDashboardTitle.setForeground(new java.awt.Color(204, 204, 204));
        CsDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CsDashboardTitle.setText("Online Sports Utility Shop");
        CsDashboard.add(CsDashboardTitle);
        CsDashboardTitle.setBounds(0, 20, 1020, 100);

        CsDashboardMenu.setBackground(new java.awt.Color(255, 255, 255));
        CsDashboardMenu.setLayout(null);

        CsDashboardMenuHelp.setText("Help");
        CsDashboardMenu.add(CsDashboardMenuHelp);
        CsDashboardMenuHelp.setBounds(560, 0, 120, 40);

        CsDashboardMenuItems.setText("Items");
        CsDashboardMenu.add(CsDashboardMenuItems);
        CsDashboardMenuItems.setBounds(0, 0, 140, 40);

        CsDashboardMenuUsers.setText("Rent Items");
        CsDashboardMenu.add(CsDashboardMenuUsers);
        CsDashboardMenuUsers.setBounds(140, 0, 140, 40);

        CsDashboardMenuAddItem.setText("Overdue Items");
        CsDashboardMenu.add(CsDashboardMenuAddItem);
        CsDashboardMenuAddItem.setBounds(280, 0, 140, 40);

        CsDashboardMenuAddUser.setText("Purchased Items");
        CsDashboardMenu.add(CsDashboardMenuAddUser);
        CsDashboardMenuAddUser.setBounds(420, 0, 140, 40);

        CsDashboard.add(CsDashboardMenu);
        CsDashboardMenu.setBounds(30, 130, 960, 40);

        CsItems.setBackground(new java.awt.Color(255, 255, 255));
        CsItems.setLayout(null);

        CsItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemId", "ItemName", "ItemBrand", "ItemColour", "ItemStock", "PurchasePrice", "RentalPrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CsItemScroll.setViewportView(CsItemsTable);

        CsItems.add(CsItemScroll);
        CsItemScroll.setBounds(0, 0, 960, 380);

        CsItemDescriptionTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsItemDescriptionTitle.setText("Description:");
        CsItems.add(CsItemDescriptionTitle);
        CsItemDescriptionTitle.setBounds(10, 410, 90, 30);

        CsItemDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsItems.add(CsItemDescription);
        CsItemDescription.setBounds(100, 410, 850, 30);

        CsDashboard.add(CsItems);
        CsItems.setBounds(30, 180, 960, 490);

        CsRentItems.setBackground(new java.awt.Color(255, 255, 255));
        CsRentItems.setLayout(null);

        CsRentItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemId", "ItemName", "ItemBrand", "ItemColour", "ItemQuantity", "RentalPrice", "RentDate", "ReturnDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CsRentItemScroll.setViewportView(CsRentItemTable);

        CsRentItems.add(CsRentItemScroll);
        CsRentItemScroll.setBounds(0, 0, 960, 380);

        CsRentItemDescriptionTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsRentItemDescriptionTitle.setText("Description:");
        CsRentItems.add(CsRentItemDescriptionTitle);
        CsRentItemDescriptionTitle.setBounds(10, 410, 90, 30);

        CsRentItemDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsRentItems.add(CsRentItemDescription);
        CsRentItemDescription.setBounds(100, 410, 850, 30);

        CsDashboard.add(CsRentItems);
        CsRentItems.setBounds(30, 180, 960, 490);

        CsOverdueItems.setBackground(new java.awt.Color(255, 255, 255));
        CsOverdueItems.setLayout(null);

        CsOverdueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemId", "ItemName", "ItemBrand", "ItemColour", "ItemQuantity", "RentalPrice", "RentalDate", "ReturnDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CsOverdueScroll.setViewportView(CsOverdueTable);

        CsOverdueItems.add(CsOverdueScroll);
        CsOverdueScroll.setBounds(0, 0, 960, 380);

        CsOverdueDescriptionTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsOverdueDescriptionTitle.setText("Description:");
        CsOverdueItems.add(CsOverdueDescriptionTitle);
        CsOverdueDescriptionTitle.setBounds(10, 410, 90, 30);

        CsOverdueDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsOverdueItems.add(CsOverdueDescription);
        CsOverdueDescription.setBounds(100, 410, 850, 30);

        CsDashboard.add(CsOverdueItems);
        CsOverdueItems.setBounds(30, 180, 960, 490);

        CsPurchasedItems.setBackground(new java.awt.Color(255, 255, 255));
        CsPurchasedItems.setLayout(null);

        CsPurchasedItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemId", "ItemName", "ItemBrand", "ItemColour", "ItemQuantity", "PurchasePrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CsPurchasedItemScroll.setViewportView(CsPurchasedItemsTable);

        CsPurchasedItems.add(CsPurchasedItemScroll);
        CsPurchasedItemScroll.setBounds(0, 0, 960, 380);

        CsPurchasedItemDescriptionTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsPurchasedItemDescriptionTitle.setText("Description:");
        CsPurchasedItems.add(CsPurchasedItemDescriptionTitle);
        CsPurchasedItemDescriptionTitle.setBounds(10, 410, 90, 30);

        CsPurchasedItemDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsPurchasedItems.add(CsPurchasedItemDescription);
        CsPurchasedItemDescription.setBounds(100, 410, 850, 30);

        CsDashboard.add(CsPurchasedItems);
        CsPurchasedItems.setBounds(30, 180, 960, 490);

        getContentPane().add(CsDashboard);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateNewAccount;
    private javax.swing.JPanel CsDashboard;
    private javax.swing.JPanel CsDashboardMenu;
    private javax.swing.JButton CsDashboardMenuAddItem;
    private javax.swing.JButton CsDashboardMenuAddUser;
    private javax.swing.JButton CsDashboardMenuHelp;
    private javax.swing.JButton CsDashboardMenuItems;
    private javax.swing.JButton CsDashboardMenuUsers;
    private javax.swing.JLabel CsDashboardTitle;
    private javax.swing.JLabel CsItemDescription;
    private javax.swing.JLabel CsItemDescriptionTitle;
    private javax.swing.JScrollPane CsItemScroll;
    private javax.swing.JPanel CsItems;
    private javax.swing.JTable CsItemsTable;
    private javax.swing.JButton CsLogout;
    private javax.swing.JLabel CsOverdueDescription;
    private javax.swing.JLabel CsOverdueDescriptionTitle;
    private javax.swing.JPanel CsOverdueItems;
    private javax.swing.JScrollPane CsOverdueScroll;
    private javax.swing.JTable CsOverdueTable;
    private javax.swing.JLabel CsPurchasedItemDescription;
    private javax.swing.JLabel CsPurchasedItemDescriptionTitle;
    private javax.swing.JScrollPane CsPurchasedItemScroll;
    private javax.swing.JPanel CsPurchasedItems;
    private javax.swing.JTable CsPurchasedItemsTable;
    private javax.swing.JLabel CsRentItemDescription;
    private javax.swing.JLabel CsRentItemDescriptionTitle;
    private javax.swing.JScrollPane CsRentItemScroll;
    private javax.swing.JTable CsRentItemTable;
    private javax.swing.JPanel CsRentItems;
    private javax.swing.JPanel LoginFields;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JLabel LoginPasswordText;
    private javax.swing.JRadioButton LoginRadioCs;
    private javax.swing.JRadioButton LoginRadioSk;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JTextField LoginUserName;
    private javax.swing.JLabel LoginUserNameText;
    private javax.swing.JLabel OnlineSportsTitle;
    private javax.swing.JLabel SkCustomerDescription;
    private javax.swing.JLabel SkCustomerDescriptionTitle;
    private javax.swing.JScrollPane SkCustomerScroll;
    private javax.swing.JTable SkCustomerTable;
    private javax.swing.JPanel SkCustomers;
    private javax.swing.JButton SkCustomersReport;
    private javax.swing.JPanel SkDashboard;
    private javax.swing.JPanel SkDashboardMenu;
    private javax.swing.JButton SkDashboardMenuAddItem;
    private javax.swing.JButton SkDashboardMenuAddUser;
    private javax.swing.JButton SkDashboardMenuHelp;
    private javax.swing.JButton SkDashboardMenuItems;
    private javax.swing.JButton SkDashboardMenuOverdues;
    private javax.swing.JButton SkDashboardMenuReport;
    private javax.swing.JButton SkDashboardMenuUsers;
    private javax.swing.JLabel SkDashboardTitle;
    private javax.swing.JLabel SkItemDescription;
    private javax.swing.JLabel SkItemDescriptionTitle;
    private javax.swing.JScrollPane SkItemScroll;
    private javax.swing.JPanel SkItems;
    private javax.swing.JButton SkItemsReport;
    private javax.swing.JTable SkItemsTable;
    private javax.swing.JButton SkLogout;
    private javax.swing.JLabel SkOverdueDescription;
    private javax.swing.JLabel SkOverdueDescriptionTitle;
    private javax.swing.JScrollPane SkOverdueScroll;
    private javax.swing.JTable SkOverdueTable;
    private javax.swing.JPanel SkOverdues;
    private javax.swing.JLabel SkReportTitle;
    private javax.swing.JPanel SkReports;
    // End of variables declaration//GEN-END:variables
}
